# Generated by Django 4.2 on 2023-04-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allusers',
            name='address',
            field=models.TextField(default='default address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allusers',
            name='phone_number',
            field=models.CharField(default='99', max_length=10),
            preserve_default=False,
        ),
    ]
